'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Book
    Public Property BookId As Integer
    Public Property BookCode As String
    Public Property Title As String
    Public Property AuthorId As Nullable(Of Integer)
    Public Property CategoryId As Nullable(Of Integer)
    Public Property PublisherId As Nullable(Of Integer)
    Public Property PublishYear As Nullable(Of Integer)
    Public Property Price As Nullable(Of Decimal)
    Public Property Quantity As Integer
    Public Property AvailableQuantity As Integer
    Public Property ImagePath As String
    Public Property Description As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property Author As Author
    Public Overridable Property Category As Category
    Public Overridable Property Publisher As Publisher
    Public Overridable Property BorrowDetails As ICollection(Of BorrowDetail) = New HashSet(Of BorrowDetail)

End Class
