'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BorrowTicket
    Public Property BorrowTicketId As Integer
    Public Property UserId As Integer
    Public Property BorrowDate As Date
    Public Property DueDate As Date
    Public Property Status As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property BorrowDetails As ICollection(Of BorrowDetail) = New HashSet(Of BorrowDetail)
    Public Overridable Property User As User
    Public Overridable Property Deposits As ICollection(Of Deposit) = New HashSet(Of Deposit)

End Class
