'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BorrowDetail
    Public Property BorrowDetailId As Integer
    Public Property BorrowTicketId As Integer
    Public Property BookId As Integer
    Public Property Quantity As Integer
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property Book As Book
    Public Overridable Property BorrowTicket As BorrowTicket

End Class
