'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Deposit
    Public Property DepositId As Integer
    Public Property BorrowTicketId As Integer
    Public Property DepositAmount As Decimal
    Public Property IsRefunded As Boolean
    Public Property RefundDate As Nullable(Of Date)
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property BorrowTicket As BorrowTicket
    Public Overridable Property Payments As ICollection(Of Payment) = New HashSet(Of Payment)

End Class
