'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Payment
    Public Property PaymentId As Integer
    Public Property DepositId As Integer
    Public Property PaymentMethod As String
    Public Property TransactionCode As String
    Public Property PaymentDate As Date
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property Deposit As Deposit

End Class
