'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Role
    Public Property RoleId As Integer
    Public Property RoleName As String
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean

    Public Overridable Property Users As ICollection(Of User) = New HashSet(Of User)

End Class
