'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property UserId As Integer
    Public Property FullName As String
    Public Property Email As String
    Public Property PasswordHash As String
    Public Property Phone As String
    Public Property IsActive As Boolean
    Public Property CreatedAt As Date
    Public Property UpdatedAt As Nullable(Of Date)
    Public Property IsDeleted As Boolean
    ' Lưu mã OTP (6 số). 
    Public Property VerificationCode As String

    ' Lưu thời hạn của mã
    Public Property CodeExpiration As DateTime?
    Public Overridable Property BorrowTickets As ICollection(Of BorrowTicket) = New HashSet(Of BorrowTicket)
    Public Overridable Property Roles As ICollection(Of Role) = New HashSet(Of Role)

End Class
